steps:

- id: "Rodando go test. alterado pra pull request"
  name: "gcr.io/cloud-builders/go"
  dir: 'go/src/greeting'
  env: ["GOPATH=."]
  args: ['test']

- id: "building image from Dockerfile.prod"
  name: "gcr.io/cloud-builders/docker"
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-go-cd:$SHORT_SHA', '-f', 'Dockerfile.prod', '.']

- id: "pushing image"
  name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/$PROJECT_ID/app-go-cd:$SHORT_SHA']

- id: "ajustando arquivo de deployment - k8s"
  name: "gcr.io/cloud-builders/gcloud"
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      sed 's#img-app-deployment#gcr.io/$PROJECT_ID/app-go-cd:$SHORT_SHA#g' go/deployment.yaml > go/deployment-new.yaml;
      cat go/deployment-new.yaml;

- id: 'deploying k8s'
  name: "gcr.io/cloud-builders/kubectl"
  args:
    - 'apply'
    - '-f'
    - 'go/deployment-new.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-laravel'
